import io
import re
from datetime import datetime
from pathlib import Path
from typing import Optional
from xml.sax.saxutils import escape
from fastapi import APIRouter, HTTPException, Depends, Query
from fastapi.responses import Response
from PIL import Image as PILImage
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, HRFlowable, KeepTogether,
)
from db import db
from auth import get_current_user
from estimates import fetch_lines, estimate_summary, DEFAULT_CONTINGENCY
from roadmap_template import STAGES

reports_router = APIRouter(prefix="/api", dependencies=[Depends(get_current_user)])

SLATE = colors.HexColor("#1E293B")
SLATE_MID = colors.HexColor("#475569")
SLATE_LIGHT = colors.HexColor("#F1F5F9")
AMBER = colors.HexColor("#B45309")
RED = colors.HexColor("#B91C1C")

ROADMAP_LABELS = {s["key"]: s["label"] for s in STAGES}
PHOTO_STAGE_LABELS = {
    "site-preparation": "Site Preparation", "base/slab": "Base / Slab", "frame": "Frame",
    "lockup": "Lockup", "fixing": "Fixing", "completion": "Completion",
    "external-works": "External Works", "unknown": "Unknown",
}

S_TITLE = ParagraphStyle("title", fontName="Helvetica-Bold", fontSize=22, leading=26, textColor=SLATE)
S_SUBTITLE = ParagraphStyle("subtitle", fontName="Helvetica-Bold", fontSize=12, leading=15, textColor=AMBER)
S_H2 = ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=13, leading=16, textColor=SLATE, spaceBefore=6)
S_BODY = ParagraphStyle("body", fontName="Helvetica", fontSize=9.5, leading=13.5, textColor=SLATE)
S_LABEL = ParagraphStyle("label", fontName="Helvetica-Bold", fontSize=9, leading=13, textColor=SLATE_MID)
S_CAPTION = ParagraphStyle("caption", fontName="Helvetica-Bold", fontSize=9.5, leading=13, textColor=AMBER)
S_BULLET = ParagraphStyle("bullet", parent=S_BODY, leftIndent=10, bulletIndent=2)
S_ISSUE = ParagraphStyle("issue", parent=S_BULLET, textColor=RED)
S_DISCLAIMER = ParagraphStyle("disclaimer", fontName="Helvetica-Oblique", fontSize=8.5, leading=12, textColor=SLATE_MID)
S_RIGHT = ParagraphStyle("right", parent=S_BODY, alignment=TA_RIGHT)


def money(v: float) -> str:
    return f"${v:,.2f}"


def aus_date(iso: Optional[str]) -> str:
    if not iso:
        return "—"
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%d/%m/%Y")
    except ValueError:
        return iso


def slug(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-") or "project"


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(SLATE_MID)
    canvas.drawString(18 * mm, 11 * mm, "Generated by BuildManager VIC")
    canvas.drawRightString(A4[0] - 18 * mm, 11 * mm, f"Page {canvas.getPageNumber()}")
    canvas.setStrokeColor(SLATE_LIGHT)
    canvas.line(18 * mm, 14.5 * mm, A4[0] - 18 * mm, 14.5 * mm)
    canvas.restoreState()


def _build_pdf(story) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=20 * mm,
        title="BuildManager VIC report",
    )
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _info_table(rows) -> Table:
    data = [[Paragraph(escape(k), S_LABEL), Paragraph(escape(v), S_BODY)] for k, v in rows]
    t = Table(data, colWidths=[38 * mm, 136 * mm])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ]))
    return t


def _site_address(project: dict) -> str:
    street = project.get("site_street") or ""
    parts = [p for p in [street, f"{project.get('site_suburb', '')} VIC {project.get('site_postcode', '')}".strip()] if p.strip()]
    return ", ".join(parts)


def _image_flowable(path: Path, max_w=158 * mm, max_h=92 * mm):
    with PILImage.open(path) as im:
        w, h = im.size
    scale = min(max_w / w, max_h / h, 1)
    return RLImage(str(path), width=w * scale, height=h * scale, hAlign="LEFT")


# ---------------- Site Diary PDF ----------------

@reports_router.get("/projects/{project_id}/site-diary.pdf")
async def site_diary_pdf(
    project_id: str,
    date_from: Optional[str] = Query(None),
    date_to: Optional[str] = Query(None),
):
    project = await db.projects.find_one({"id": project_id}, {"_id": 0})
    if not project:
        raise HTTPException(status_code=404, detail="Project not found.")
    for name, value in (("date_from", date_from), ("date_to", date_to)):
        if value and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
            raise HTTPException(status_code=400, detail=f"{name} must be in YYYY-MM-DD format.")

    photos = await db.photo_analyses.find({"project_id": project_id}, {"_id": 0}).sort("created_at", 1).to_list(500)
    if date_from:
        photos = [p for p in photos if p["created_at"][:10] >= date_from]
    if date_to:
        photos = [p for p in photos if p["created_at"][:10] <= date_to]
    if not photos:
        raise HTTPException(status_code=400, detail="No analysed photos found for this project in the selected date range.")

    period = f"{aus_date(photos[0]['created_at'])} – {aus_date(photos[-1]['created_at'])}"
    story = [
        Paragraph("SITE DIARY", S_TITLE),
        Paragraph(escape(project["name"]), S_SUBTITLE),
        Spacer(1, 5 * mm),
        _info_table([
            ("Site address", _site_address(project)),
            ("Client", project.get("client_name") or "—"),
            ("Builder", f"{project.get('builder_name') or '—'} — Reg. {project.get('builder_registration') or '—'}"),
            ("Period covered", period),
            ("Generated", datetime.now().strftime("%d/%m/%Y")),
        ]),
        Spacer(1, 3 * mm),
        HRFlowable(width="100%", thickness=1.2, color=AMBER),
        Spacer(1, 4 * mm),
    ]

    # Group entries by calendar date (ascending)
    groups = {}
    for p in photos:
        groups.setdefault(p["created_at"][:10], []).append(p)

    for date_key in sorted(groups):
        story.append(Paragraph(aus_date(f"{date_key}T00:00:00"), S_H2))
        story.append(HRFlowable(width="100%", thickness=0.6, color=SLATE_LIGHT))
        story.append(Spacer(1, 2.5 * mm))
        for p in groups[date_key]:
            a = p["analysis"]
            stage = PHOTO_STAGE_LABELS.get(a["identified_stage"], a["identified_stage"])
            caption = f"Stage: {stage} &nbsp;·&nbsp; Confidence: {a['confidence'].title()}"
            entry = []
            file_path = Path(p["file_path"]) if p.get("file_path") else None
            if file_path and file_path.exists():
                entry.append(_image_flowable(file_path))
                entry.append(Spacer(1, 1.5 * mm))
            entry.append(Paragraph(caption, S_CAPTION))
            story.append(KeepTogether(entry))
            story.append(Spacer(1, 1.5 * mm))
            if a.get("progress_notes"):
                story.append(Paragraph(escape(a["progress_notes"]), S_BODY))
            if p.get("notes"):
                story.append(Spacer(1, 1 * mm))
                story.append(Paragraph(f"<b>PM note:</b> {escape(p['notes'])}", S_BODY))
            if a.get("observations"):
                story.append(Spacer(1, 1.5 * mm))
                story.append(Paragraph("Observations", S_LABEL))
                for obs in a["observations"]:
                    story.append(Paragraph(escape(obs), S_BULLET, bulletText="•"))
            if a.get("potential_issues"):
                story.append(Spacer(1, 1.5 * mm))
                story.append(Paragraph("Flagged issues", ParagraphStyle("il", parent=S_LABEL, textColor=RED)))
                for issue in a["potential_issues"]:
                    story.append(Paragraph(escape(issue), S_ISSUE, bulletText="!"))
            story.append(Spacer(1, 6 * mm))

    pdf = _build_pdf(story)
    filename = f"Site-Diary-{slug(project['name'])}.pdf"
    return Response(content=pdf, media_type="application/pdf",
                    headers={"Content-Disposition": f'attachment; filename="{filename}"'})


# ---------------- Estimate PDF (client-facing) ----------------

@reports_router.get("/projects/{project_id}/estimate.pdf")
async def estimate_pdf(project_id: str):
    project = await db.projects.find_one({"id": project_id}, {"_id": 0})
    if not project:
        raise HTTPException(status_code=404, detail="Project not found.")
    lines = await fetch_lines(project_id)
    if not lines:
        raise HTTPException(status_code=400, detail="No estimate lines to export. Add lines in the Budget tab first.")

    pct = project.get("contingency_pct", DEFAULT_CONTINGENCY)
    summary = estimate_summary(lines, pct, project.get("contract_value", 0))

    dbi = project.get("dbi_policy_number") or "—"
    dbi_exp = project.get("dbi_expiry")
    dbi_line = f"Domestic Building Insurance: {dbi}" + (f" — expires {aus_date(dbi_exp)}" if dbi_exp else "")

    story = [
        Paragraph(escape(project.get("builder_name") or "Builder"), S_TITLE),
        Paragraph(f"Registered Building Practitioner: {escape(project.get('builder_registration') or '—')}", S_BODY),
        Paragraph(escape(dbi_line), S_BODY),
        Spacer(1, 4 * mm),
        HRFlowable(width="100%", thickness=1.2, color=AMBER),
        Spacer(1, 4 * mm),
        Paragraph("PRELIMINARY COST ESTIMATE", S_SUBTITLE),
        Spacer(1, 3 * mm),
        _info_table([
            ("Client", project.get("client_name") or "—"),
            ("Site address", _site_address(project)),
            ("Project", project["name"]),
            ("Date", datetime.now().strftime("%d/%m/%Y")),
        ]),
        Spacer(1, 5 * mm),
    ]

    # Lines table grouped by stage (lines arrive pre-sorted by stage order)
    col_widths = [79 * mm, 18 * mm, 24 * mm, 26 * mm, 27 * mm]
    data = [[Paragraph("Description", ParagraphStyle("th", parent=S_LABEL, textColor=colors.white)),
             Paragraph("Qty", ParagraphStyle("thr", parent=S_LABEL, textColor=colors.white, alignment=TA_RIGHT)),
             Paragraph("Unit", ParagraphStyle("thu", parent=S_LABEL, textColor=colors.white)),
             Paragraph("Rate", ParagraphStyle("thr2", parent=S_LABEL, textColor=colors.white, alignment=TA_RIGHT)),
             Paragraph("Amount ex-GST", ParagraphStyle("thr3", parent=S_LABEL, textColor=colors.white, alignment=TA_RIGHT))]]
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), SLATE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, SLATE_LIGHT),
    ]
    row = 1
    current_stage = None
    for line in lines:
        if line["stage_key"] != current_stage:
            current_stage = line["stage_key"]
            label = ROADMAP_LABELS.get(current_stage, current_stage)
            data.append([Paragraph(f"Stage — {escape(label)}", ParagraphStyle("st", parent=S_LABEL, textColor=SLATE)), "", "", "", ""])
            style_cmds += [("SPAN", (0, row), (-1, row)), ("BACKGROUND", (0, row), (-1, row), SLATE_LIGHT)]
            row += 1
        qty = f"{line['quantity']:g}"
        data.append([
            Paragraph(escape(line["description"]), S_BODY),
            Paragraph(qty, S_RIGHT),
            Paragraph(escape(line.get("unit") or "—"), S_BODY),
            Paragraph(money(line["rate"]), S_RIGHT),
            Paragraph(money(line["line_total"]), S_RIGHT),
        ])
        row += 1

    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle(style_cmds))
    story.append(table)
    story.append(Spacer(1, 5 * mm))

    totals = [
        ("Subtotal (ex GST)", money(summary["subtotal_ex_gst"]), S_BODY),
        ("GST (10%)", money(summary["gst"]), S_BODY),
        (f"Contingency ({pct:g}%)", money(summary["contingency_amount"]), S_BODY),
        ("Estimated total", money(summary["grand_total"]), None),
    ]
    tdata = []
    for label, value, _ in totals:
        bold = label == "Estimated total"
        ls = ParagraphStyle("tl", parent=S_BODY, alignment=TA_RIGHT, fontName="Helvetica-Bold" if bold else "Helvetica",
                            fontSize=11 if bold else 9.5, textColor=AMBER if bold else SLATE)
        vs = ParagraphStyle("tv", parent=ls)
        tdata.append([Paragraph(escape(label), ls), Paragraph(value, vs)])
    ttable = Table(tdata, colWidths=[134 * mm, 40 * mm], hAlign="RIGHT")
    ttable.setStyle(TableStyle([
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LINEABOVE", (0, -1), (-1, -1), 0.8, SLATE),
    ]))
    story.append(KeepTogether([ttable]))
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(
        "Estimate only — subject to final quotation and site conditions. Rates indicative for western Victoria 2025.",
        S_DISCLAIMER))

    pdf = _build_pdf(story)
    filename = f"Estimate-{slug(project['name'])}.pdf"
    return Response(content=pdf, media_type="application/pdf",
                    headers={"Content-Disposition": f'attachment; filename="{filename}"'})
