# Victorian residential construction roadmap template for a licensed builder.
# Stage weights follow the typical Victorian domestic building progress payment
# schedule (Domestic Building Contracts Act 1995): deposit 5%, base 10%,
# frame 15%, lock-up 35%, fixing 25%, completion 10%.

STAGES = [
    {"key": "pre-construction", "label": "Pre-Construction & Compliance", "number": 1, "weight": 5},
    {"key": "base", "label": "Base", "number": 2, "weight": 10},
    {"key": "frame", "label": "Frame", "number": 3, "weight": 15},
    {"key": "lockup", "label": "Lockup", "number": 4, "weight": 35},
    {"key": "fixing", "label": "Fixing", "number": 5, "weight": 25},
    {"key": "completion", "label": "Completion", "number": 6, "weight": 10},
]

STAGE_KEYS = {s["key"] for s in STAGES}

# Each entry: (title, description/compliance note, is_mandatory_inspection)
ROADMAP_TEMPLATE = {
    "pre-construction": [
        ("Confirm builder registration current (DB-U/CDB-U)",
         "Work must be carried out under a registered building practitioner (VBA registration current).", False),
        ("Sign Major Domestic Building Contract",
         "Required for domestic building work over $10,000 — Domestic Building Contracts Act 1995 (Vic).", False),
        ("Obtain Domestic Building Insurance",
         "Warranty insurance required for work over $16,000 before taking a deposit; maximum deposit 5%.", False),
        ("Architectural/working drawings finalised",
         "Full working drawings and specifications signed off by client.", False),
        ("Planning permit (if required by council)",
         "Confirm with local council whether a planning permit is required before building permit.", False),
        ("Engage Registered Building Surveyor (RBS)",
         "Appoint the RBS who will issue the building permit and carry out mandatory inspections.", False),
        ("Building permit issued",
         "Building permit must be issued by the RBS before any works commence on site.", False),
        ("Site safety plan / OHS preparation",
         "Prepare site safety plan; notify WorkSafe Victoria if required for the works.", False),
        ("Utilities & site establishment",
         "Temporary power, water, site fencing, sediment control in place.", False),
    ],
    "base": [
        ("Site cut & excavation, set-out",
         "Site levelled and building set-out verified against approved drawings.", False),
        ("Under-slab plumbing/drainage rough-in",
         "Sanitary and stormwater drainage installed and tested before pour.", False),
        ("Termite protection installed",
         "Termite management system installed in accordance with AS 3660.1.", False),
        ("MANDATORY INSPECTION: Pre-pour footings/slab approval",
         "RBS must inspect and approve footings/slab steel BEFORE the pour proceeds.", True),
        ("Footings/slab poured",
         "Concrete poured and cured; base stage complete for progress payment purposes.", False),
    ],
    "frame": [
        ("Wall & roof framing erected",
         "Frame erected per engineering and approved drawings.", False),
        ("Roof trusses installed",
         "Trusses installed and fixed per manufacturer layout and tie-down schedule.", False),
        ("Windows/external door frames installed",
         "Window and external door frames fitted within frame.", False),
        ("MANDATORY INSPECTION: Frame approval",
         "RBS frame inspection approval required before frame is covered.", True),
    ],
    "lockup": [
        ("Roof covering complete",
         "Roofing installed including sarking, flashings and gutters.", False),
        ("External wall cladding/brickwork",
         "Brickwork/cladding complete including damp-proof courses and weep holes.", False),
        ("External doors & windows installed",
         "Building secured at lockup stage — external doors and windows in place.", False),
        ("Electrical & plumbing rough-in",
         "Electrical wiring and plumbing pipework roughed-in within walls and ceilings.", False),
        ("Insulation installed",
         "Wall and ceiling insulation installed to energy report requirements.", False),
    ],
    "fixing": [
        ("Plasterboard installed",
         "Plasterboard hung, set and sanded throughout.", False),
        ("Internal doors, architraves, skirting",
         "Fixing carpentry complete.", False),
        ("Kitchen cabinetry & wet area fit-out",
         "Kitchen and wet area cabinetry installed.", False),
        ("Waterproofing to wet areas",
         "Wet area waterproofing applied in accordance with AS 3740.", False),
        ("MANDATORY INSPECTION: Wet area waterproofing approval",
         "RBS approval of wet area waterproofing where required by the building permit.", True),
        ("Tiling",
         "Wall and floor tiling to wet areas and specified rooms.", False),
        ("Painting",
         "Internal painting complete.", False),
    ],
    "completion": [
        ("Fit-off electrical & plumbing, appliances",
         "Power points, light fittings, tapware, fixtures and appliances installed and commissioned.", False),
        ("Final finishes & site clean",
         "Final touch-ups, builder's clean and site clear.", False),
        ("MANDATORY INSPECTION: Final inspection by RBS",
         "RBS carries out the final mandatory inspection of the completed building work.", True),
        ("Occupancy Permit / Certificate of Final Inspection issued",
         "Issued by the RBS — building cannot be occupied without it (new builds require an Occupancy Permit).", False),
        ("Handover pack to client",
         "Warranties, appliance manuals, compliance certificates and keys handed to client.", False),
        ("Defects liability period commences",
         "Defects liability period per contract begins at handover.", False),
    ],
}
