"""The site supervisor's own checklist, phase A to O.

The 25-step sequence in build_sequence.py says what order the TRADES come in.
This says what the SUPERVISOR has to do — the permits, the consents, the checks
before something is covered up, the certificates collected on the way out. None
of it has a package or a price against it, so none of it appeared anywhere, and
it is exactly the work that stops a job when it is missed.

Written for a single-storey slab-on-ground house in Wyndham. The stamped
building-permit drawings and the inspection schedule on the permit take priority
over anything here.

Two things earn their own treatment:

  * HOLD POINTS (phases marked hold=True). Work must not proceed past these
    until the surveyor has passed the stage. They are called out separately
    rather than buried in a list of ticks.
  * LEAD TIMES (remind_days). Wyndham wants road-reserve applications 20
    business days ahead and the asset protection report within five days of
    starting. Something that has to be applied for weeks early is worth
    surfacing weeks early.

Numbering follows the supervisor's own list so an item can be quoted by number.
"""
from typing import Optional

# kind drives the icon, the wording and whether the item is chased.
# Things that come from someone else (permit, inspection, certificate,
# notification, insurance, order) block work and are reminded about.
EXTERNAL_KINDS = {"permit", "inspection", "certificate", "notification",
                  "insurance", "order", "hold", "service"}

PHASES = [
    # ---------------------------------------------------------------- A
    {
        "key": "a", "letter": "A", "name": "Before construction starts",
        "detail": "Everything that must be true before a machine turns up. Most delays on a job are made here.",
        "steps": [1],
        "items": [
            {"n": 1, "key": "permit-obtained", "kind": "permit",
             "name": "Obtain and review the complete building permit"},
            {"n": 2, "key": "builder-named", "kind": "check",
             "name": "Confirm the correct builder is named on the permit"},
            {"n": 3, "key": "permit-dates", "kind": "check",
             "name": "Check permit commencement and completion expiry dates"},
            {"n": 4, "key": "inspections-listed", "kind": "inspection",
             "name": "List every mandatory inspection stated on the permit",
             "note": "The permit is the authority on which stages apply to this job — not this checklist."},
            {"n": 5, "key": "permit-conditions", "kind": "check",
             "name": "Review all permit conditions, reports and consents"},
            {"n": 6, "key": "document-set", "kind": "document",
             "name": "Prepare a controlled set of current construction documents",
             "sub": ["Architectural drawings", "Engineering and slab drawings", "Soil report",
                     "Frame and truss drawings", "Energy / NatHERS report",
                     "Specifications and selections", "Electrical plan", "Plumbing / drainage plan",
                     "Heating and cooling plan", "Developer-approved drawings, if applicable"]},
            {"n": 7, "key": "drawing-discrepancies", "kind": "check",
             "name": "Resolve discrepancies between architectural and engineering drawings"},
            {"n": 8, "key": "levels-and-setbacks", "kind": "check",
             "name": "Confirm finished-floor level, setbacks, easements and legal point of discharge"},
            {"n": 9, "key": "water-sewer-stormwater", "kind": "service",
             "name": "Confirm water tapping, sewer connection and stormwater approvals"},
            {"n": 10, "key": "electricity-connection", "kind": "service",
             "name": "Confirm electricity-pit location, meter-box location and connection process"},
            {"n": 11, "key": "other-services", "kind": "service",
             "name": "Arrange gas, NBN and other services if required"},
            {"n": 12, "key": "long-lead-orders", "kind": "order",
             "name": "Order long-lead items", "remind_days": 56,
             "note": "Trusses and windows are made to order. Left late, they hold up the whole job.",
             "sub": ["Frames and trusses", "Windows", "Bricks or cladding", "Roofing",
                     "Garage door", "Kitchen and cabinetry", "Heating and cooling", "Appliances"]},
            {"n": 13, "key": "trade-scopes", "kind": "check",
             "name": "Finalise written scopes and prices with every trade"},
            {"n": 14, "key": "licences-and-insurance", "kind": "insurance",
             "name": "Verify builder and trade licences, registrations and insurance"},
            {"n": 15, "key": "program-and-hold-points", "kind": "record",
             "name": "Establish the construction program and inspection hold points"},
            {"n": 16, "key": "swms", "kind": "safety",
             "name": "Obtain SWMS for high-risk construction work before that work starts",
             "note": "WorkSafe Victoria requires the SWMS before the high-risk work begins, not after."},
            {"n": 17, "key": "road-reserve-consent", "kind": "permit", "remind_days": 28,
             "name": "Apply for Wyndham road-reserve consent",
             "note": "Wyndham requires these applications at least 20 business days before the work.",
             "sub": ["The crossover", "Footpath or nature strip",
                     "Water, sewer, gas or electricity connections",
                     "Council stormwater infrastructure"]},
        ],
    },
    # ---------------------------------------------------------------- B
    {
        "key": "b", "letter": "B", "name": "Site establishment",
        "detail": "Making the site legal, safe and usable before anyone works on it.",
        "steps": [1],
        "items": [
            {"n": 18, "key": "asset-protection", "kind": "permit", "remind_days": 5,
             "name": "Submit Wyndham's Asset Protection and Pre-Commencement Report",
             "note": "Due within five days before starting."},
            {"n": 19, "key": "dilapidation-photos", "kind": "record",
             "name": "Photograph existing roads, kerbs, drains, footpaths, crossover and nature strip",
             "note": "This is your only defence against a Council asset-damage claim later."},
            {"n": 20, "key": "temp-fencing", "kind": "site",
             "name": "Install temporary construction fencing and a lockable gate"},
            {"n": 21, "key": "signage", "kind": "site",
             "name": "Display required builder, permit and safety signage"},
            {"n": 22, "key": "amenities", "kind": "site",
             "name": "Provide a site toilet, drinking water, first aid and waste facilities"},
            {"n": 23, "key": "temp-power", "kind": "service",
             "name": "Arrange temporary builder's electricity or a suitable alternative"},
            {"n": 24, "key": "sediment-controls", "kind": "site",
             "name": "Install sediment and erosion controls"},
            {"n": 25, "key": "stabilised-access", "kind": "site",
             "name": "Create a stabilised access point for trucks and machinery"},
            {"n": 26, "key": "protect-neighbours", "kind": "site",
             "name": "Protect neighbouring property and Council assets"},
            {"n": 27, "key": "byda", "kind": "notification",
             "name": "Obtain Before You Dig Australia service information"},
            {"n": 28, "key": "locate-services", "kind": "check",
             "name": "Locate existing underground services before excavation"},
            {"n": 29, "key": "adjoining-protection", "kind": "check",
             "name": "Confirm any required adjoining-property protection work is complete"},
            {"n": 30, "key": "registers", "kind": "record",
             "name": "Establish a site diary, inspection register and certificate register"},
        ],
    },
    # ---------------------------------------------------------------- C
    {
        "key": "c", "letter": "C", "name": "Survey set-out and site cut",
        "detail": "Getting the house in the right place, at the right height, on ground that will hold it.",
        "steps": [2],
        "items": [
            {"n": 31, "key": "surveyor-setout", "kind": "check",
             "name": "Have the licensed surveyor confirm boundaries and set out the house"},
            {"n": 32, "key": "setbacks-check", "kind": "check",
             "name": "Check setbacks, orientation, easements and crossover alignment"},
            {"n": 33, "key": "datum-and-ffl", "kind": "check",
             "name": "Establish the survey datum and finished-floor level"},
            {"n": 34, "key": "clear-vegetation", "kind": "site",
             "name": "Clear vegetation and rubbish as legally permitted"},
            {"n": 35, "key": "strip-topsoil", "kind": "site",
             "name": "Strip and stockpile or remove topsoil"},
            {"n": 36, "key": "site-cut", "kind": "site",
             "name": "Complete the site cut and required filling"},
            {"n": 37, "key": "retaining-walls", "kind": "site",
             "name": "Construct retaining walls early where they support the building platform"},
            {"n": 38, "key": "cut-fill-levels", "kind": "check",
             "name": "Check cut-and-fill levels against the engineering plan"},
            {"n": 39, "key": "compaction-test", "kind": "test",
             "name": "Test fill compaction where engineered fill is used"},
            {"n": 40, "key": "unexpected-ground", "kind": "check",
             "name": "Stop and consult the engineer if unexpected soft soil, uncontrolled fill, water or rock is found"},
            {"n": 41, "key": "recheck-setout", "kind": "check",
             "name": "Recheck building set-out before footing excavation"},
        ],
    },
    # ---------------------------------------------------------------- D
    {
        "key": "d", "letter": "D", "name": "Footings and slab preparation",
        "detail": "Everything that gets buried. Check it now or open the slab later.",
        "steps": [3, 4],
        "items": [
            {"n": 42, "key": "excavate-footings", "kind": "site",
             "name": "Excavate footings and edge beams according to engineering"},
            {"n": 43, "key": "footing-check", "kind": "check",
             "name": "Check footing depth, width, bearing material and excavation cleanliness"},
            {"n": 44, "key": "plumber-under-slab", "kind": "check",
             "name": "Have the plumber install the under-slab work",
             "sub": ["Under-slab sanitary drains", "Sewer connection provisions", "Waste risers",
                     "Water-entry sleeves", "Stormwater sleeves where required"]},
            {"n": 45, "key": "drainage-test", "kind": "test",
             "name": "Have the plumber test the underground drainage before covering it"},
            {"n": 46, "key": "electrician-under-slab", "kind": "check",
             "name": "Have the electrician review and install, where required",
             "sub": ["Kitchen-island conduit", "Underground consumer-mains conduit",
                     "Slab reinforcement bonding", "Floor outlets",
                     "Conduits to garage, gate, shed, pool or EV charger",
                     "Future solar and battery conduits"]},
            {"n": 47, "key": "comms-conduits", "kind": "check",
             "name": "Install communications / NBN conduits where required"},
            {"n": 48, "key": "conduit-locations", "kind": "check",
             "name": "Confirm every pipe and conduit location against cabinetry and floor plans"},
            {"n": 49, "key": "photograph-under-slab", "kind": "record",
             "name": "Photograph and measure all under-slab services"},
            {"n": 50, "key": "sand-and-vapour-barrier", "kind": "site",
             "name": "Install the sand base, vapour barrier and slab penetrations"},
            {"n": 51, "key": "termite-management", "kind": "site",
             "name": "Install termite-management components"},
            {"n": 52, "key": "formwork-and-reo", "kind": "site",
             "name": "Install formwork, waffle pods, reinforcement, beams, starter bars and tie-downs"},
            {"n": 53, "key": "pre-slab-check", "kind": "check",
             "name": "Check the slab set-up before it is signed off",
             "sub": ["Slab dimensions and diagonals", "Garage step-down", "Shower recesses",
                     "Door thresholds", "Plumbing riser positions", "Reinforcement cover",
                     "Vapour-barrier condition"]},
            {"n": 54, "key": "engineer-inspection", "kind": "inspection",
             "name": "Arrange any required geotechnical or structural-engineer inspection"},
        ],
    },
    # ------------------------------------------------------- HOLD POINT
    {
        "key": "hold-slab", "letter": "★", "name": "Mandatory hold point — footing / pre-slab",
        "detail": "Concrete does not go in until this has passed. The permit specifies the exact stages, and you must notify the surveyor when each is ready.",
        "steps": [5], "hold": True,
        "items": [
            {"n": 55, "key": "notify-surveyor", "kind": "hold",
             "name": "Notify the relevant building surveyor that the footing / pre-slab stage is ready"},
            {"n": 56, "key": "inspection-passed", "kind": "hold",
             "name": "Do not pour until the inspection has passed and defects are corrected"},
        ],
    },
    # ---------------------------------------------------------------- E
    {
        "key": "e", "letter": "E", "name": "Concrete slab",
        "detail": "Pour, cure, protect, then check what you actually got.",
        "steps": [6],
        "items": [
            {"n": 57, "key": "pour-preparation", "kind": "check",
             "name": "Confirm concrete grade, quantity, pump access and weather conditions"},
            {"n": 58, "key": "reo-not-displaced", "kind": "check",
             "name": "Check that reinforcement and vapour barrier have not been displaced"},
            {"n": 59, "key": "supervise-pour", "kind": "check",
             "name": "Supervise concrete placement, vibration, levelling and finishing"},
            {"n": 60, "key": "dockets", "kind": "record",
             "name": "Retain concrete delivery dockets and test results where applicable"},
            {"n": 61, "key": "curing", "kind": "site",
             "name": "Commence curing immediately"},
            {"n": 62, "key": "protect-slab", "kind": "site",
             "name": "Protect the slab from premature loading and damage"},
            {"n": 63, "key": "post-cure-check", "kind": "check",
             "name": "After curing, check the slab",
             "sub": ["Slab dimensions", "Levels and surface finish", "Cracking or honeycombing",
                     "Rebates and step-downs", "Plumbing locations"]},
            {"n": 64, "key": "defect-engineering-advice", "kind": "check",
             "name": "Obtain engineering advice for material defects rather than accepting cosmetic patching"},
        ],
    },
    # ---------------------------------------------------------------- F
    {
        "key": "f", "letter": "F", "name": "Frame and trusses",
        "detail": "The last chance to fix anything structural before it is covered.",
        "steps": [7, 8],
        "items": [
            {"n": 65, "key": "slab-vs-frame", "kind": "check",
             "name": "Compare slab measurements with the frame layout before delivery"},
            {"n": 66, "key": "check-delivery", "kind": "check",
             "name": "Check delivered frames and trusses against approved shop drawings"},
            {"n": 67, "key": "store-timber", "kind": "site",
             "name": "Store timber correctly and protect it from prolonged weather exposure"},
            {"n": 68, "key": "supervise-erection", "kind": "check",
             "name": "Supervise wall-frame erection"},
            {"n": 69, "key": "wall-locations", "kind": "check",
             "name": "Check wall locations, room dimensions and door/window openings"},
            {"n": 70, "key": "beams-and-lintels", "kind": "site",
             "name": "Install beams, lintels, columns and structural connections"},
            {"n": 71, "key": "roof-trusses", "kind": "site",
             "name": "Install roof trusses according to the truss layout"},
            {"n": 72, "key": "bracing", "kind": "check",
             "name": "Check permanent and temporary bracing"},
            {"n": 73, "key": "tie-downs", "kind": "check",
             "name": "Verify tie-downs, anchors, straps and hold-down bolts"},
            {"n": 74, "key": "frame-alignment", "kind": "check",
             "name": "Check frames for plumb, level, straightness and alignment"},
            {"n": 75, "key": "noggins", "kind": "check",
             "name": "Ensure adequate support and noggins are in place for",
             "sub": ["Kitchen cabinetry", "Wall-mounted televisions", "Handrails", "Shower screens",
                     "Towel rails and accessories", "Heavy light fittings", "Air-conditioning equipment"],
             "note": "Nobody remembers this until the TV bracket goes into plasterboard."},
            {"n": 76, "key": "no-unauthorised-cutting", "kind": "check",
             "name": "Ensure trades do not cut, drill or notch structural components without approval"},
            {"n": 77, "key": "engineer-frame-inspection", "kind": "inspection",
             "name": "Arrange structural-engineer inspection where required"},
            {"n": 78, "key": "frame-defects", "kind": "check",
             "name": "Have the carpenter rectify all frame defects"},
        ],
    },
    # ------------------------------------------------------- HOLD POINT
    {
        "key": "hold-frame", "letter": "★", "name": "Mandatory hold point — frame",
        "detail": "Nothing that conceals the frame goes on until this has passed.",
        "steps": [9], "hold": True,
        "items": [
            {"n": 79, "key": "book-frame-inspection", "kind": "hold",
             "name": "Book the mandatory frame inspection"},
            {"n": 80, "key": "no-concealment", "kind": "hold",
             "name": "Do not install plaster, wall cladding or anything else that conceals the frame until it passes"},
        ],
    },
    # ---------------------------------------------------------------- G
    {
        "key": "g", "letter": "G", "name": "Roof and lock-up",
        "detail": "Getting the building watertight and secure.",
        "steps": [10, 11, 12],
        "items": [
            {"n": 81, "key": "scaffold", "kind": "safety",
             "name": "Install compliant scaffolding and fall protection"},
            {"n": 82, "key": "fascia-and-gutters", "kind": "site", "name": "Install fascia and gutters"},
            {"n": 83, "key": "roof-cover", "kind": "site",
             "name": "Install roof sarking, roof sheets or roof tiles"},
            {"n": 84, "key": "flashings", "kind": "site",
             "name": "Complete valleys, flashings, penetrations and cappings"},
            {"n": 85, "key": "temporary-downpipes", "kind": "check",
             "name": "Temporarily connect downpipes so roof water does not undermine the slab"},
            {"n": 86, "key": "wall-wrap", "kind": "site",
             "name": "Install external wall wrap with properly sealed laps"},
            {"n": 87, "key": "windows-and-doors", "kind": "site",
             "name": "Install windows and external doors"},
            {"n": 88, "key": "window-flashing", "kind": "check",
             "name": "Check window sill flashing, head flashing and drainage paths"},
            {"n": 89, "key": "windows-match-energy", "kind": "check",
             "name": "Confirm windows match energy-report requirements"},
            {"n": 90, "key": "cladding", "kind": "site",
             "name": "Install brickwork or external cladding"},
            {"n": 91, "key": "brick-check", "kind": "check",
             "name": "Check brick cavities, ties, damp-proof courses, flashings and weep holes"},
            {"n": 92, "key": "articulation-joints", "kind": "check",
             "name": "Check articulation joints against engineering"},
            {"n": 93, "key": "eaves-and-trims", "kind": "site",
             "name": "Install eaves, soffits and external trims"},
            {"n": 94, "key": "garage-door", "kind": "site",
             "name": "Install the garage door or temporarily secure the opening"},
            {"n": 95, "key": "weatherproofing", "kind": "check",
             "name": "Check roof and window weatherproofing"},
            {"n": 96, "key": "lock-up", "kind": "site",
             "name": "Secure the building at lock-up"},
            {"n": 97, "key": "independent-lockup-inspection", "kind": "inspection",
             "name": "Arrange an independent lock-up inspection if desired"},
        ],
    },
    # ---------------------------------------------------------------- H
    {
        "key": "h", "letter": "H", "name": "Services rough-in",
        "detail": "Three trades in the same walls. Coordinate them before they arrive, photograph everything before it is covered.",
        "steps": [13, 14],
        "items": [
            {"n": 98, "key": "final-plans-issued", "kind": "document",
             "name": "Issue final coordinated plans to all rough-in trades"},
            {"n": 99, "key": "coordination-meeting", "kind": "meeting",
             "name": "Conduct a site meeting with the plumber, electrician, HVAC installer and carpenter"},
            {"n": 100, "key": "mark-locations", "kind": "check",
             "name": "Mark every fixture, power point, switch, light, tap, drain, grille and appliance location"},
            {"n": 101, "key": "plumbing-rough-in", "kind": "check",
             "name": "Have the plumber rough-in",
             "sub": ["Hot and cold water", "Internal waste", "Gas, if applicable",
                     "Baths and showers", "Refrigerator and dishwasher connections",
                     "Hot-water-system connections"]},
            {"n": 102, "key": "pressure-test", "kind": "test",
             "name": "Pressure-test plumbing before it is concealed"},
            {"n": 103, "key": "hvac-rough-in", "kind": "check",
             "name": "Install heating and cooling ducts, refrigerant lines and condensate drains"},
            {"n": 104, "key": "electrical-rough-in", "kind": "check",
             "name": "Have the electrician rough-in",
             "sub": ["Power points", "Lighting", "Switches", "Switchboard", "Smoke alarms",
                     "Appliances", "Data, security, solar, battery and EV provisions"]},
            {"n": 105, "key": "comms-cabling", "kind": "check",
             "name": "Install NBN and other communication cabling"},
            {"n": 106, "key": "services-clash", "kind": "check",
             "name": "Check that plumbing, ducts and cables do not conflict"},
            {"n": 107, "key": "structural-cuts", "kind": "check",
             "name": "Check that structural members have not been excessively cut or drilled"},
            {"n": 108, "key": "penetration-seals", "kind": "check",
             "name": "Install fire, acoustic and weather seals around penetrations as required"},
            {"n": 109, "key": "exhaust-discharge", "kind": "check",
             "name": "Confirm exhaust fans discharge outside, not into the roof space"},
            {"n": 110, "key": "photograph-walls", "kind": "record",
             "name": "Photograph every wall and ceiling before insulation"},
            {"n": 111, "key": "record-measurements", "kind": "record",
             "name": "Record measurements for concealed plumbing and cabling"},
            {"n": 112, "key": "trade-tests", "kind": "test",
             "name": "Have each trade test its rough-in"},
        ],
    },
    # ---------------------------------------------------------------- I
    {
        "key": "i", "letter": "I", "name": "Pre-plaster and insulation",
        "detail": "The last look inside the walls.",
        "steps": [15],
        "items": [
            {"n": 113, "key": "frame-dry", "kind": "check",
             "name": "Confirm the frame is dry, straight and free of unresolved defects"},
            {"n": 114, "key": "pre-plaster-inspection", "kind": "inspection",
             "name": "Complete a detailed pre-plaster inspection"},
            {"n": 115, "key": "bath-check", "kind": "check",
             "name": "Check bath installation and concealed plumbing"},
            {"n": 116, "key": "noggin-check", "kind": "check",
             "name": "Check all required cabinetry supports and noggins"},
            {"n": 117, "key": "seal-penetrations", "kind": "site",
             "name": "Seal external-wall and ceiling penetrations"},
            {"n": 118, "key": "install-insulation", "kind": "site",
             "name": "Install wall and ceiling insulation according to the energy report"},
            {"n": 119, "key": "insulation-check", "kind": "check",
             "name": "Check the insulation",
             "sub": ["Correct R-value", "No missing sections", "No excessive compression",
                     "Proper fit around cables and pipes",
                     "Complete coverage behind baths and services"]},
            {"n": 120, "key": "acoustic-insulation", "kind": "site",
             "name": "Install acoustic insulation where specified"},
            {"n": 121, "key": "insulation-evidence", "kind": "certificate",
             "name": "Collect insulation installation evidence or certificates required by the surveyor"},
            {"n": 122, "key": "no-plaster-until-clear", "kind": "check",
             "name": "Do not allow plaster to begin until all rough-in defects are rectified"},
        ],
    },
    # ---------------------------------------------------------------- J
    {
        "key": "j", "letter": "J", "name": "Plaster and internal fixing",
        "detail": "Linings, trim and doors.",
        "steps": [16, 18],
        "items": [
            {"n": 123, "key": "ceiling-plaster", "kind": "site", "name": "Install ceiling plasterboard"},
            {"n": 124, "key": "wall-linings", "kind": "site",
             "name": "Install wall and wet-area linings"},
            {"n": 125, "key": "cornices", "kind": "site",
             "name": "Install cornices or square-set finishes"},
            {"n": 126, "key": "stopping-and-sanding", "kind": "check",
             "name": "Complete stopping, sanding and surface checks"},
            {"n": 127, "key": "doors-and-jambs", "kind": "site",
             "name": "Install internal door jambs and doors"},
            {"n": 128, "key": "internal-trim", "kind": "site",
             "name": "Install skirting, architraves, window reveals and other internal trim"},
            {"n": 129, "key": "stairs-and-balustrades", "kind": "site",
             "name": "Install stairs, balustrades and handrails where applicable"},
            {"n": 130, "key": "pre-paint-check", "kind": "check",
             "name": "Check door openings, ceiling lines and plaster surfaces before painting"},
        ],
    },
    # ---------------------------------------------------------------- K
    {
        "key": "k", "letter": "K", "name": "Waterproofing, tiling and cabinetry",
        "detail": "The exact order of cabinetry, painting and tiling can vary according to the finishes selected.",
        "steps": [17],
        "items": [
            {"n": 131, "key": "shower-falls", "kind": "check",
             "name": "Confirm shower falls, floor wastes, hobs and recesses"},
            {"n": 132, "key": "substrate-prep", "kind": "site",
             "name": "Prepare wet-area substrates correctly"},
            {"n": 133, "key": "waterproofing", "kind": "site",
             "name": "Apply waterproofing to bathrooms, ensuite, laundry and other required areas"},
            {"n": 134, "key": "photograph-waterproofing", "kind": "record",
             "name": "Photograph the completed waterproofing before it is covered"},
            {"n": 135, "key": "waterproofing-certificate", "kind": "certificate",
             "name": "Obtain the waterproofing certificate or declaration required by the surveyor"},
            {"n": 136, "key": "independent-wp-inspection", "kind": "inspection",
             "name": "Arrange an independent waterproofing inspection if possible"},
            {"n": 137, "key": "screeds", "kind": "site",
             "name": "Install screeds and confirm drainage falls"},
            {"n": 138, "key": "tiling", "kind": "site", "name": "Install wall and floor tiles"},
            {"n": 139, "key": "tile-check", "kind": "check",
             "name": "Check tile alignment, falls, grout and movement joints"},
            {"n": 140, "key": "cabinetry", "kind": "site",
             "name": "Install kitchen, bathroom, laundry and wardrobe cabinetry"},
            {"n": 141, "key": "cabinetry-check", "kind": "check",
             "name": "Check cabinetry dimensions, levels and appliance clearances"},
            {"n": 142, "key": "benchtops", "kind": "site",
             "name": "Template and install stone or other benchtops"},
            {"n": 143, "key": "splashbacks", "kind": "site", "name": "Install splashbacks"},
            {"n": 144, "key": "protect-wet-areas", "kind": "check",
             "name": "Protect completed waterproofing, tiles and cabinetry from following trades"},
        ],
    },
    # ---------------------------------------------------------------- L
    {
        "key": "l", "letter": "L", "name": "Painting and final finishes",
        "detail": "Finishes go in, and from here everything needs protecting from the next trade.",
        "steps": [19, 22],
        "items": [
            {"n": 145, "key": "surface-preparation", "kind": "site",
             "name": "Complete surface preparation and sealing"},
            {"n": 146, "key": "paint", "kind": "site",
             "name": "Apply internal and external paint systems"},
            {"n": 147, "key": "paint-check", "kind": "check",
             "name": "Check coverage, colour, finish and damage"},
            {"n": 148, "key": "flooring", "kind": "site",
             "name": "Install timber, vinyl, laminate or carpet flooring"},
            {"n": 149, "key": "wardrobes-and-hardware", "kind": "site",
             "name": "Install wardrobes, shelving and internal hardware"},
            {"n": 150, "key": "screens-and-mirrors", "kind": "site",
             "name": "Install shower screens and mirrors"},
            {"n": 151, "key": "caulking", "kind": "site",
             "name": "Complete caulking and sealant work"},
            {"n": 152, "key": "protect-finishes", "kind": "check",
             "name": "Protect finished floors and painted surfaces"},
        ],
    },
    # ---------------------------------------------------------------- M
    {
        "key": "m", "letter": "M", "name": "Electrical, plumbing and HVAC fit-off",
        "detail": "Fixtures on, everything tested, and the certificates collected while the trade is still on site.",
        "steps": [20, 21],
        "items": [
            {"n": 153, "key": "electrical-fit-off", "kind": "check",
             "name": "Have the electrician install",
             "sub": ["Switches and power points", "Light fittings", "Switchboard equipment",
                     "Smoke alarms", "Exhaust fans", "Appliances and isolators"]},
            {"n": 154, "key": "prescribed-electrical-inspection", "kind": "inspection",
             "name": "Arrange the prescribed electrical inspection"},
            {"n": 155, "key": "electrical-work-request", "kind": "notification", "remind_days": 21,
             "name": "Submit the Electrical Work Request for permanent supply"},
            {"n": 156, "key": "meter-energisation", "kind": "service",
             "name": "Coordinate meter installation and energisation"},
            {"n": 157, "key": "electrical-tests", "kind": "test",
             "name": "Test RCDs, circuits, lights, appliances and interconnected smoke alarms"},
            {"n": 158, "key": "certificates-electrical-safety", "kind": "certificate",
             "name": "Obtain all Certificates of Electrical Safety",
             "note": "Energy Safe Victoria. Collect it before the electrician leaves site."},
            {"n": 159, "key": "plumbing-fit-off", "kind": "check",
             "name": "Have the plumber install",
             "sub": ["Toilets", "Taps and basins", "Sinks", "Baths", "Hot-water system",
                     "Gas appliances", "Dishwasher and refrigerator connections"]},
            {"n": 160, "key": "plumbing-commission", "kind": "test",
             "name": "Pressure-test and commission plumbing"},
            {"n": 161, "key": "drain-test", "kind": "test",
             "name": "Test every drain for flow and leakage"},
            {"n": 162, "key": "plumbing-certificates", "kind": "certificate",
             "name": "Obtain required plumbing compliance certificates"},
            {"n": 163, "key": "hvac-fit-off", "kind": "site",
             "name": "Complete HVAC grilles, controllers and outdoor units"},
            {"n": 164, "key": "hvac-test", "kind": "test",
             "name": "Test heating, cooling and condensate drainage"},
            {"n": 165, "key": "garage-door-motor", "kind": "test",
             "name": "Install and test the garage-door motor"},
        ],
    },
    # ---------------------------------------------------------------- N
    {
        "key": "n", "letter": "N", "name": "External works",
        "detail": "Drainage, driveway, Council assets and the ground falling away from the house.",
        "steps": [23],
        "items": [
            {"n": 166, "key": "stormwater-to-lpod", "kind": "site",
             "name": "Complete stormwater drainage to the approved legal point of discharge"},
            {"n": 167, "key": "downpipes", "kind": "site", "name": "Permanently connect all downpipes"},
            {"n": 168, "key": "rainwater-tank", "kind": "site",
             "name": "Install and commission the rainwater tank and pump where required"},
            {"n": 169, "key": "authority-requirements", "kind": "service",
             "name": "Complete sewer and water-authority requirements"},
            {"n": 170, "key": "trench-inspection", "kind": "inspection",
             "name": "Confirm all external service trenches are inspected before backfilling"},
            {"n": 171, "key": "finished-ground-levels", "kind": "check",
             "name": "Establish finished ground levels that drain away from the house"},
            {"n": 172, "key": "weep-holes-clear", "kind": "check",
             "name": "Keep weep holes, termite barriers and inspection zones clear"},
            {"n": 173, "key": "paths-and-dpc", "kind": "check",
             "name": "Construct paths and paving without bridging the damp-proof course"},
            {"n": 174, "key": "driveway-and-crossover", "kind": "permit",
             "name": "Construct the driveway and Council crossover under the relevant approval"},
            {"n": 175, "key": "fencing-and-fittings", "kind": "site",
             "name": "Install fencing, gates, letterbox and clothesline"},
            {"n": 176, "key": "landscaping", "kind": "site",
             "name": "Complete landscaping required by the permit"},
            {"n": 177, "key": "reinstate-nature-strip", "kind": "site",
             "name": "Reinstate the nature strip and repair damaged Council assets"},
            {"n": 178, "key": "remove-waste", "kind": "site",
             "name": "Remove construction waste and redundant temporary services"},
            {"n": 179, "key": "clean-drains", "kind": "site",
             "name": "Clean gutters, drains, pits and the roof"},
        ],
    },
    # ---------------------------------------------------------------- O
    {
        "key": "o", "letter": "O", "name": "Completion and Occupancy Permit",
        "detail": "Nobody moves in until the Occupancy Permit is issued. Occupying before it is an offence.",
        "steps": [24, 25],
        "items": [
            {"n": 180, "key": "supervisor-inspection", "kind": "inspection",
             "name": "Conduct the supervisor's complete quality inspection"},
            {"n": 181, "key": "full-test", "kind": "test",
             "name": "Test everything",
             "sub": ["Every tap, toilet and drain", "Hot-water delivery", "Heating and cooling",
                     "Lights and power points", "Smoke alarms", "Appliances", "Windows and locks",
                     "Garage-door safety system", "Rainwater system"]},
            {"n": 182, "key": "check-against-plans", "kind": "check",
             "name": "Check the house against the stamped plans, specifications and approved variations"},
            {"n": 183, "key": "independent-prehandover", "kind": "inspection",
             "name": "Conduct an independent pre-handover inspection if desired"},
            {"n": 184, "key": "defect-list", "kind": "record",
             "name": "Prepare a written defect list"},
            {"n": 185, "key": "rectify-and-clean", "kind": "check",
             "name": "Rectify all defects and clean the house"},
            {"n": 186, "key": "collect-certificates", "kind": "certificate",
             "name": "Collect the documents required by the building surveyor",
             "sub": ["Plumbing compliance certificates", "Electrical safety certificates",
                     "Structural and frame certificates", "Truss documentation",
                     "Waterproofing documentation", "Insulation and energy-efficiency documentation",
                     "Termite-management certificate", "Glazing certificate", "Roofing documentation",
                     "Smoke-alarm evidence", "BAL documentation, if applicable",
                     "As-built survey, if requested"]},
            {"n": 187, "key": "apply-occupancy-permit", "kind": "permit", "remind_days": 21,
             "name": "Apply for the Occupancy Permit"},
            {"n": 188, "key": "final-inspection", "kind": "hold",
             "name": "Book the mandatory final inspection"},
            {"n": 189, "key": "rectify-surveyor-items", "kind": "check",
             "name": "Rectify every item identified by the building surveyor"},
            {"n": 190, "key": "occupancy-permit-issued", "kind": "hold",
             "name": "Obtain the Occupancy Permit before anyone moves into the house",
             "note": "Occupying a new house before this is issued is an offence."},
            {"n": 191, "key": "handover", "kind": "record",
             "name": "Provide the owner with keys, warranties, manuals, certificates and maintenance instructions"},
            {"n": 192, "key": "archive", "kind": "record",
             "name": "Keep a complete copy of approved drawings, certificates and site photographs"},
            {"n": 193, "key": "council-asset-damage", "kind": "check",
             "name": "Address any Council asset damage identified after occupancy"},
        ],
    },
]

# Not tickable — these run for the whole job, and a checkbox would be a lie.
# Shown as a standing panel so they stay in front of the supervisor.
ONGOING = [
    "Keep the current stamped drawings on site.",
    "Check work before it is concealed or paid for.",
    "Maintain a daily site diary and photographic record.",
    "Book trades, materials and mandatory inspections.",
    "Verify deliveries against the specification.",
    "Keep the site secure, clean and safe.",
    "Check licences, insurance and SWMS.",
    "Record delays, weather and instructions.",
    "Raise RFIs where drawings conflict.",
    "Obtain written approval for variations.",
    "Prevent unauthorised substitutions.",
    "Protect completed work from later trades.",
    "Track the budget, invoices and progress payments.",
    "Maintain respectful access, noise and waste controls.",
    "Collect certificates immediately after each trade completes.",
    "Never proceed beyond a mandatory inspection stage until it has passed.",
]

FOOTNOTE = ("The building surveyor checks regulatory compliance at nominated stages. They are not "
            "your quality-control inspector, so keep doing your own detailed checks throughout.")

BY_KEY = {p["key"]: p for p in PHASES}
ITEM_COUNT = sum(len(p["items"]) for p in PHASES)


def items_for(phase_key: str) -> list:
    phase = BY_KEY.get(phase_key)
    return phase["items"] if phase else []


def find(action_key: str) -> Optional[tuple]:
    """Resolve "phase:item" to the phase and item it names."""
    phase_key, _, item_key = action_key.partition(":")
    phase = BY_KEY.get(phase_key)
    if not phase:
        return None
    for item in phase["items"]:
        if item["key"] == item_key:
            return phase, item
    return None


def phase_for_step(step_n: int) -> Optional[dict]:
    """Which phase of the checklist a sequence step belongs to."""
    return next((p for p in PHASES if step_n in p["steps"]), None)


# ---------------------------------------------------------------------------
# Who actually does the work.
#
# The checklist is for confirming; the board is for acting. So every item here
# that is delivered by a trade names that trade, and the API resolves it to the
# board package that covers it. An item with no package behind it is work
# nobody is booked for — which is the thing worth knowing early, and the reason
# this mapping exists rather than the two screens just sitting side by side.
#
# match: keywords tried against a package title, most specific first. A package
# is looked for across the whole board, not just this phase's steps, because one
# package routinely covers two visits (the plumber's rough-in and fit-off are
# usually the same engagement).
# type:  the trade type used if a package has to be created, and the fallback
#        when no title matches.
# items: the checklist items this trade delivers.
TRADE_WORK = {
    "b": [
        {"key": "site-setup", "work": "Site establishment", "type": "other",
         "match": ["site establish", "fencing and amenities", "site set-up", "site setup"],
         "items": ["temp-fencing", "signage", "amenities", "temp-power",
                   "sediment-controls", "stabilised-access", "protect-neighbours"]},
    ],
    "c": [
        {"key": "surveyor", "work": "Surveyor set-out", "type": "other",
         "match": ["survey", "set-out", "setout"],
         "items": ["surveyor-setout", "setbacks-check", "datum-and-ffl", "recheck-setout"]},
        {"key": "earthworks", "work": "Site cut and earthworks", "type": "excavator-earthworks",
         "match": ["site cut", "earthwork", "excavat", "site prep", "bulk earth"],
         "items": ["clear-vegetation", "strip-topsoil", "site-cut", "retaining-walls"]},
        {"key": "soil-testing", "work": "Compaction testing", "type": "other",
         "match": ["compaction", "geotech", "soil test"],
         "items": ["compaction-test"]},
    ],
    "d": [
        {"key": "footings", "work": "Footing excavation", "type": "excavator-earthworks",
         "match": ["footing", "excavat", "pier", "pile"],
         "items": ["excavate-footings"]},
        {"key": "plumber-underslab", "work": "Under-slab plumbing", "type": "plumber",
         "match": ["plumb", "drainage", "sewer"],
         "items": ["plumber-under-slab", "drainage-test"]},
        {"key": "sparky-underslab", "work": "Under-slab electrical", "type": "electrician",
         "match": ["electric", "sparky"],
         "items": ["electrician-under-slab", "comms-conduits"]},
        {"key": "termite", "work": "Termite management", "type": "other",
         "match": ["termite"],
         "items": ["termite-management"]},
        {"key": "slab", "work": "Concrete slab", "type": "concreter",
         "match": ["slab", "waffle", "concret"],
         "items": ["sand-and-vapour-barrier", "formwork-and-reo"]},
    ],
    "e": [
        {"key": "slab", "work": "Concrete slab", "type": "concreter",
         "match": ["slab", "waffle", "concret", "pour"],
         "items": ["supervise-pour", "curing", "protect-slab"]},
    ],
    "f": [
        {"key": "carpenter-frame", "work": "Frame and trusses", "type": "carpenter",
         "match": ["frame", "truss", "carpent"],
         "items": ["check-delivery", "store-timber", "supervise-erection", "wall-locations",
                   "beams-and-lintels", "roof-trusses", "bracing", "tie-downs",
                   "frame-alignment", "noggins", "frame-defects"]},
    ],
    "g": [
        {"key": "scaffold", "work": "Scaffolding", "type": "other",
         "match": ["scaffold"],
         "items": ["scaffold"]},
        {"key": "roofer", "work": "Roofing and gutters", "type": "roofer",
         "match": ["roof", "gutter", "fascia"],
         "items": ["fascia-and-gutters", "roof-cover", "flashings", "temporary-downpipes"]},
        {"key": "windows", "work": "Windows and external doors", "type": "other",
         "match": ["window", "external door", "glazing"],
         "items": ["wall-wrap", "windows-and-doors"]},
        {"key": "cladding", "work": "Brickwork or cladding", "type": "bricklayer",
         "match": ["brick", "cladding", "hebel", "masonry", "render"],
         "items": ["cladding", "eaves-and-trims"]},
        {"key": "garage-door", "work": "Garage door", "type": "other",
         "match": ["garage door"],
         "items": ["garage-door"]},
    ],
    "h": [
        {"key": "plumber-rough", "work": "Plumbing rough-in", "type": "plumber",
         "match": ["plumb"],
         "items": ["plumbing-rough-in", "pressure-test"]},
        {"key": "hvac-rough", "work": "Heating and cooling", "type": "other",
         "match": ["heating", "cooling", "hvac", "air con", "aircon", "refrigerat"],
         "items": ["hvac-rough-in"]},
        {"key": "sparky-rough", "work": "Electrical rough-in", "type": "electrician",
         "match": ["electric", "sparky"],
         "items": ["electrical-rough-in", "comms-cabling"]},
    ],
    "i": [
        {"key": "insulation", "work": "Insulation", "type": "other",
         "match": ["insulation", "batts"],
         "items": ["install-insulation", "acoustic-insulation"]},
    ],
    "j": [
        {"key": "plasterer", "work": "Plastering", "type": "plasterer",
         "match": ["plaster", "lining", "cornice"],
         "items": ["ceiling-plaster", "wall-linings", "cornices", "stopping-and-sanding"]},
        {"key": "fixing-carpentry", "work": "Internal fixing carpentry", "type": "carpenter",
         "match": ["internal fix", "fixing carpent", "skirting", "architrave", "internal door"],
         "items": ["doors-and-jambs", "internal-trim", "stairs-and-balustrades"]},
    ],
    "k": [
        {"key": "waterproofer", "work": "Wet area waterproofing", "type": "waterproofer",
         "match": ["waterproof"],
         "items": ["substrate-prep", "waterproofing"]},
        {"key": "tiler", "work": "Tiling", "type": "tiler",
         "match": ["til", "screed"],
         "items": ["screeds", "tiling"]},
        {"key": "cabinetry", "work": "Cabinetry and benchtops", "type": "other",
         "match": ["cabinet", "joinery", "kitchen", "benchtop", "splashback"],
         "items": ["cabinetry", "benchtops", "splashbacks"]},
    ],
    "l": [
        {"key": "painter", "work": "Painting", "type": "painter",
         "match": ["paint"],
         "items": ["surface-preparation", "paint"]},
        {"key": "flooring", "work": "Flooring", "type": "other",
         "match": ["floor", "carpet", "vinyl", "timber floor"],
         "items": ["flooring"]},
        {"key": "wardrobes", "work": "Wardrobes and shelving", "type": "other",
         "match": ["wardrobe", "shelving", "robe"],
         "items": ["wardrobes-and-hardware"]},
        {"key": "screens", "work": "Shower screens and mirrors", "type": "other",
         "match": ["shower screen", "mirror", "glazier"],
         "items": ["screens-and-mirrors", "caulking"]},
    ],
    "m": [
        {"key": "sparky-fitoff", "work": "Electrical fit-off", "type": "electrician",
         "match": ["electric", "sparky"],
         "items": ["electrical-fit-off", "electrical-tests"]},
        {"key": "plumber-fitoff", "work": "Plumbing fit-off", "type": "plumber",
         "match": ["plumb"],
         "items": ["plumbing-fit-off", "plumbing-commission", "drain-test"]},
        {"key": "hvac-fitoff", "work": "Heating and cooling", "type": "other",
         "match": ["heating", "cooling", "hvac", "air con", "aircon"],
         "items": ["hvac-fit-off", "hvac-test"]},
        {"key": "garage-motor", "work": "Garage door", "type": "other",
         "match": ["garage door"],
         "items": ["garage-door-motor"]},
    ],
    "n": [
        {"key": "stormwater", "work": "Stormwater and external plumbing", "type": "plumber",
         "match": ["stormwater", "external plumb", "downpipe", "tank"],
         "items": ["stormwater-to-lpod", "downpipes", "rainwater-tank"]},
        {"key": "driveway", "work": "Driveway, paths and crossover", "type": "concreter",
         "match": ["driveway", "crossover", "path", "paving"],
         "items": ["paths-and-dpc", "driveway-and-crossover"]},
        {"key": "fencing", "work": "Fencing, gates and letterbox", "type": "other",
         "match": ["fenc", "gate", "letterbox", "clothesline"],
         "items": ["fencing-and-fittings"]},
        {"key": "landscaping", "work": "Landscaping and nature strip", "type": "other",
         "match": ["landscap", "nature strip", "turf", "garden"],
         "items": ["landscaping", "reinstate-nature-strip", "finished-ground-levels"]},
        {"key": "site-clean", "work": "Waste removal and site clean", "type": "other",
         "match": ["clean", "waste", "rubbish", "skip"],
         "items": ["remove-waste", "clean-drains"]},
    ],
    "o": [
        {"key": "builders-clean", "work": "Builder's clean", "type": "other",
         "match": ["clean"],
         "items": ["rectify-and-clean"]},
    ],
}

# item key -> the trade entry that delivers it, for the phase it sits in.
TRADE_FOR_ITEM = {
    (phase_key, item_key): entry
    for phase_key, entries in TRADE_WORK.items()
    for entry in entries
    for item_key in entry["items"]
}


def trade_work_for(phase_key: str) -> list:
    return TRADE_WORK.get(phase_key, [])


def trade_for_item(phase_key: str, item_key: str) -> Optional[dict]:
    return TRADE_FOR_ITEM.get((phase_key, item_key))
